import fs from "fs";
import path from "path";
import { QueryResult } from "./query.js";
import { ProjectIndex } from "./storage.js";

// ─── Targets ──────────────────────────────────────────────────────────────────

export type Target = "claude" | "cursor" | "copilot" | "codex";

const TARGET_OUTPUT_FILES: Record<Target, string> = {
  claude: "CLAUDE.md",
  cursor: ".cursorrules",
  copilot: ".github/copilot-instructions.md",
  codex: "AGENTS.md",
};

// ─── Generator ────────────────────────────────────────────────────────────────

export function generateContextFile(
  index: ProjectIndex,
  results: QueryResult[],
  userQuery: string,
  target: Target,
  projectPath: string = process.cwd()
): string {
  const outputFile = TARGET_OUTPUT_FILES[target];
  const outputPath = path.join(projectPath, outputFile);

  // Ensure parent dir exists (for copilot which needs .github/)
  const parentDir = path.dirname(outputPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  const content = buildContent(index, results, userQuery, target);
  fs.writeFileSync(outputPath, content, "utf-8");

  return outputPath;
}

// ─── Content Builder ──────────────────────────────────────────────────────────

function buildContent(
  index: ProjectIndex,
  results: QueryResult[],
  userQuery: string,
  target: Target
): string {
  const now = new Date().toLocaleString();
  const header = getHeader(target);

  const projectOverview = `# ${index.projectName}
${header}

> Generated by smartctx on ${now}
> Task: "${userQuery}"
> Showing ${results.length} most relevant files out of ${index.totalFiles} total

---
`;

  const relevantFiles = results.map((r, i) => {
    const exports = r.file.exports.length > 0
      ? `\n  - **Exports:** ${r.file.exports.slice(0, 5).join(", ")}`
      : "";
    const deps = r.file.dependencies.length > 0
      ? `\n  - **Key deps:** ${r.file.dependencies.slice(0, 4).join(", ")}`
      : "";
    const tags = r.file.tags.length > 0
      ? `\n  - **Tags:** ${r.file.tags.join(", ")}`
      : "";

    return `### ${i + 1}. \`${r.file.path}\`
  - ${r.file.summary}${exports}${deps}${tags}`;
  }).join("\n\n");

  const allFiles = Object.values(index.files)
    .map((f) => `- \`${f.path}\` — ${f.summary}`)
    .join("\n");

  const footer = `

---

## All Project Files (for reference)

${allFiles}

---
*smartctx — https://github.com/yourusername/smartctx*
*Last full sync: ${index.lastSync}*
`;

  return `${projectOverview}
## Relevant Files for Your Task

${relevantFiles}
${footer}`;
}

// ─── Headers per AI tool ──────────────────────────────────────────────────────

function getHeader(target: Target): string {
  switch (target) {
    case "claude":
      return `<!-- Claude Code Context File — auto-generated by smartctx -->
<!-- Read this file to understand the project before making changes -->`;
    case "cursor":
      return `# Cursor Rules — auto-generated by smartctx`;
    case "copilot":
      return `<!-- GitHub Copilot Instructions — auto-generated by smartctx -->`;
    case "codex":
      return `# Codex Agent Instructions — auto-generated by smartctx`;
  }
}

// ─── Token Estimate ───────────────────────────────────────────────────────────

export function estimateTokensSaved(
  totalFiles: number,
  avgFileSizeBytes: number,
  relevantFiles: number
): number {
  // Rough: 1 token ≈ 4 bytes
  const fullTokens = (totalFiles * avgFileSizeBytes) / 4;
  const smartTokens = (relevantFiles * avgFileSizeBytes) / 4 + 2000; // 2k for index overhead
  return Math.max(0, Math.round(fullTokens - smartTokens));
}
