import fs from "fs";
import path from "path";
import { QueryResult } from "./query.js";
import { ProjectIndex } from "./storage.js";
import { getTarget, TargetDef } from "./targets.js";

export type Target = string;

export interface GenerateResult {
  target: string;
  outputPath: string;
}

export function generateContextFile(
  index: ProjectIndex,
  results: QueryResult[],
  userQuery: string,
  target: Target,
  projectPath: string = process.cwd()
): string {
  const def = getTarget(target);
  if (!def) {
    throw new Error(
      `Unknown target "${target}". Run: smartctx targets list`
    );
  }
  return writeForTarget(def, index, results, userQuery, projectPath);
}

export function generateContextFiles(
  index: ProjectIndex,
  results: QueryResult[],
  userQuery: string,
  targets: Target[],
  projectPath: string = process.cwd()
): GenerateResult[] {
  const out: GenerateResult[] = [];
  for (const t of targets) {
    const def = getTarget(t);
    if (!def) {
      throw new Error(
        `Unknown target "${t}". Run: smartctx targets list`
      );
    }
    out.push({
      target: t,
      outputPath: writeForTarget(def, index, results, userQuery, projectPath),
    });
  }
  return out;
}

function writeForTarget(
  def: TargetDef,
  index: ProjectIndex,
  results: QueryResult[],
  userQuery: string,
  projectPath: string
): string {
  const outputPath = path.join(projectPath, def.outputFile);
  const parentDir = path.dirname(outputPath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }
  const content = buildContent(index, results, userQuery, def);
  fs.writeFileSync(outputPath, content, "utf-8");
  return outputPath;
}

function buildContent(
  index: ProjectIndex,
  results: QueryResult[],
  userQuery: string,
  def: TargetDef
): string {
  const now = new Date().toLocaleString();

  const projectOverview = `# ${index.projectName}
${def.header}

> Generated by smartctx on ${now}
> Task: "${userQuery}"
> Showing ${results.length} most relevant files out of ${index.totalFiles} total

---
`;

  const relevantFiles = results
    .map((r, i) => {
      const exports =
        r.file.exports.length > 0
          ? `\n  - **Exports:** ${r.file.exports.slice(0, 5).join(", ")}`
          : "";
      const deps =
        r.file.dependencies.length > 0
          ? `\n  - **Key deps:** ${r.file.dependencies.slice(0, 4).join(", ")}`
          : "";
      const tags =
        r.file.tags.length > 0
          ? `\n  - **Tags:** ${r.file.tags.join(", ")}`
          : "";

      return `### ${i + 1}. \`${r.file.path}\`
  - ${r.file.summary}${exports}${deps}${tags}`;
    })
    .join("\n\n");

  const allFiles = Object.values(index.files)
    .map((f) => `- \`${f.path}\` — ${f.summary}`)
    .join("\n");

  const footer = `

---

## All Project Files (for reference)

${allFiles}

---
*smartctx — https://www.npmjs.com/package/smartctx*
*Last full sync: ${index.lastSync}*
`;

  return `${projectOverview}
## Relevant Files for Your Task

${relevantFiles}
${footer}`;
}

export function estimateTokensSaved(
  totalFiles: number,
  avgFileSizeBytes: number,
  relevantFiles: number
): number {
  const fullTokens = (totalFiles * avgFileSizeBytes) / 4;
  const smartTokens = (relevantFiles * avgFileSizeBytes) / 4 + 2000;
  return Math.max(0, Math.round(fullTokens - smartTokens));
}
