import fs from "fs";
import path from "path";
import os from "os";

export interface TargetDef {
  name: string;
  outputFile: string;
  header: string;
  detectFiles?: string[];
}

export const BUILT_IN_TARGETS: Record<string, TargetDef> = {
  claude: {
    name: "claude",
    outputFile: "CLAUDE.md",
    header:
      "<!-- Claude Code Context File — auto-generated by smartctx -->\n<!-- Read this file to understand the project before making changes -->",
    detectFiles: ["CLAUDE.md", ".claude/"],
  },
  cursor: {
    name: "cursor",
    outputFile: ".cursorrules",
    header: "# Cursor Rules — auto-generated by smartctx",
    detectFiles: [".cursorrules", ".cursor/"],
  },
  copilot: {
    name: "copilot",
    outputFile: ".github/copilot-instructions.md",
    header: "<!-- GitHub Copilot Instructions — auto-generated by smartctx -->",
    detectFiles: [".github/copilot-instructions.md"],
  },
  codex: {
    name: "codex",
    outputFile: "AGENTS.md",
    header: "# Agent Instructions — auto-generated by smartctx",
    detectFiles: ["AGENTS.md"],
  },
  windsurf: {
    name: "windsurf",
    outputFile: ".windsurfrules",
    header: "# Windsurf Rules — auto-generated by smartctx",
    detectFiles: [".windsurfrules", ".windsurf/"],
  },
  cline: {
    name: "cline",
    outputFile: ".clinerules",
    header: "# Cline Rules — auto-generated by smartctx",
    detectFiles: [".clinerules"],
  },
  aider: {
    name: "aider",
    outputFile: "CONVENTIONS.md",
    header: "# Aider Conventions — auto-generated by smartctx",
    detectFiles: ["CONVENTIONS.md", ".aider.conf.yml"],
  },
  continue: {
    name: "continue",
    outputFile: ".continuerules",
    header: "# Continue Rules — auto-generated by smartctx",
    detectFiles: [".continuerules", ".continue/"],
  },
  gemini: {
    name: "gemini",
    outputFile: "GEMINI.md",
    header: "<!-- Gemini CLI Context — auto-generated by smartctx -->",
    detectFiles: ["GEMINI.md", ".gemini/"],
  },
  zed: {
    name: "zed",
    outputFile: ".rules",
    header: "# Zed AI Rules — auto-generated by smartctx",
    detectFiles: [".rules", ".zed/"],
  },
};

const USER_TARGETS_FILE = path.join(os.homedir(), ".smartctx", "targets.json");

export function loadUserTargets(): Record<string, TargetDef> {
  if (!fs.existsSync(USER_TARGETS_FILE)) return {};
  try {
    const raw = fs.readFileSync(USER_TARGETS_FILE, "utf-8");
    const parsed = JSON.parse(raw) as Record<string, TargetDef>;
    const out: Record<string, TargetDef> = {};
    for (const [key, def] of Object.entries(parsed)) {
      if (def && typeof def.outputFile === "string") {
        out[key] = {
          name: def.name ?? key,
          outputFile: def.outputFile,
          header: def.header ?? `# ${key} — auto-generated by smartctx`,
          detectFiles: def.detectFiles,
        };
      }
    }
    return out;
  } catch {
    return {};
  }
}

export function saveUserTargets(targets: Record<string, TargetDef>): void {
  const dir = path.dirname(USER_TARGETS_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(USER_TARGETS_FILE, JSON.stringify(targets, null, 2));
}

export function getAllTargets(): Record<string, TargetDef> {
  return { ...BUILT_IN_TARGETS, ...loadUserTargets() };
}

export function getTarget(name: string): TargetDef | undefined {
  return getAllTargets()[name.toLowerCase()];
}

export function addUserTarget(def: TargetDef): void {
  const user = loadUserTargets();
  user[def.name.toLowerCase()] = def;
  saveUserTargets(user);
}

export function removeUserTarget(name: string): boolean {
  const key = name.toLowerCase();
  const user = loadUserTargets();
  if (!(key in user)) return false;
  delete user[key];
  saveUserTargets(user);
  return true;
}

export function parseTargets(input: string): string[] {
  return input
    .split(",")
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
}

export function detectTarget(projectPath: string): string | undefined {
  const targets = getAllTargets();
  for (const [key, def] of Object.entries(targets)) {
    if (!def.detectFiles) continue;
    for (const marker of def.detectFiles) {
      const full = path.join(projectPath, marker);
      if (fs.existsSync(full)) return key;
    }
  }
  return undefined;
}
