from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import List, Literal

from smartctx.query import QueryResult
from smartctx.storage import ProjectIndex

# ── Targets ──────────────────────────────────────────────────────────────────

Target = Literal["claude", "cursor", "copilot", "codex"]

TARGET_OUTPUT_FILES: dict[str, str] = {
    "claude": "CLAUDE.md",
    "cursor": ".cursorrules",
    "copilot": ".github/copilot-instructions.md",
    "codex": "AGENTS.md",
}


# ── Generator ────────────────────────────────────────────────────────────────


def generate_context_file(
    index: ProjectIndex,
    results: List[QueryResult],
    user_query: str,
    target: Target,
    project_path: str | None = None,
) -> str:
    project_path = project_path or os.getcwd()
    output_file = TARGET_OUTPUT_FILES[target]
    output_path = Path(project_path) / output_file

    # Ensure parent dir exists (for copilot which needs .github/)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = _build_content(index, results, user_query, target)
    output_path.write_text(content, "utf-8")

    return str(output_path)


# ── Content Builder ──────────────────────────────────────────────────────────


def _build_content(
    index: ProjectIndex,
    results: List[QueryResult],
    user_query: str,
    target: Target,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = _get_header(target)

    project_overview = (
        f"# {index.projectName}\n"
        f"{header}\n\n"
        f"> Generated by smartctx on {now}\n"
        f'> Task: "{user_query}"\n'
        f"> Showing {len(results)} most relevant files out of {index.totalFiles} total\n\n"
        f"---\n"
    )

    relevant_parts: List[str] = []
    for i, r in enumerate(results):
        exports = (
            f"\n  - **Exports:** {', '.join(r.file.exports[:5])}"
            if r.file.exports else ""
        )
        deps = (
            f"\n  - **Key deps:** {', '.join(r.file.dependencies[:4])}"
            if r.file.dependencies else ""
        )
        tags = (
            f"\n  - **Tags:** {', '.join(r.file.tags)}"
            if r.file.tags else ""
        )
        relevant_parts.append(
            f"### {i + 1}. `{r.file.path}`\n"
            f"  - {r.file.summary}{exports}{deps}{tags}"
        )

    relevant_files = "\n\n".join(relevant_parts)

    all_files = "\n".join(
        f"- `{f.path}` \u2014 {f.summary}" for f in index.files.values()
    )

    footer = (
        f"\n\n---\n\n"
        f"## All Project Files (for reference)\n\n"
        f"{all_files}\n\n"
        f"---\n"
        f"*smartctx \u2014 https://github.com/Abdullahbutt-143/smartctx*\n"
        f"*Last full sync: {index.lastSync}*\n"
    )

    return (
        f"{project_overview}\n"
        f"## Relevant Files for Your Task\n\n"
        f"{relevant_files}"
        f"{footer}"
    )


# ── Headers per AI tool ──────────────────────────────────────────────────────


def _get_header(target: Target) -> str:
    headers = {
        "claude": (
            "<!-- Claude Code Context File \u2014 auto-generated by smartctx -->\n"
            "<!-- Read this file to understand the project before making changes -->"
        ),
        "cursor": "# Cursor Rules \u2014 auto-generated by smartctx",
        "copilot": "<!-- GitHub Copilot Instructions \u2014 auto-generated by smartctx -->",
        "codex": "# Codex Agent Instructions \u2014 auto-generated by smartctx",
    }
    return headers[target]


# ── Token Estimate ───────────────────────────────────────────────────────────


def estimate_tokens_saved(
    total_files: int,
    avg_file_size_bytes: float,
    relevant_files: int,
) -> int:
    full_tokens = (total_files * avg_file_size_bytes) / 4
    smart_tokens = (relevant_files * avg_file_size_bytes) / 4 + 2000
    return max(0, round(full_tokens - smart_tokens))
