from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List

from smartctx.query import QueryResult
from smartctx.storage import ProjectIndex
from smartctx.targets import TargetDef, get_target

Target = str


@dataclass
class GenerateResult:
    target: str
    outputPath: str


def generate_context_file(
    index: ProjectIndex,
    results: List[QueryResult],
    user_query: str,
    target: Target,
    project_path: str | None = None,
) -> str:
    project_path = project_path or os.getcwd()
    definition = get_target(target)
    if definition is None:
        raise ValueError(f'Unknown target "{target}". Run: smartctx targets list')
    return _write_for_target(definition, index, results, user_query, project_path)


def generate_context_files(
    index: ProjectIndex,
    results: List[QueryResult],
    user_query: str,
    targets: List[Target],
    project_path: str | None = None,
) -> List[GenerateResult]:
    project_path = project_path or os.getcwd()
    out: List[GenerateResult] = []
    for t in targets:
        definition = get_target(t)
        if definition is None:
            raise ValueError(f'Unknown target "{t}". Run: smartctx targets list')
        out.append(
            GenerateResult(
                target=t,
                outputPath=_write_for_target(
                    definition, index, results, user_query, project_path
                ),
            )
        )
    return out


def _write_for_target(
    definition: TargetDef,
    index: ProjectIndex,
    results: List[QueryResult],
    user_query: str,
    project_path: str,
) -> str:
    output_path = Path(project_path) / definition.outputFile
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = _build_content(index, results, user_query, definition)
    output_path.write_text(content, "utf-8")
    return str(output_path)


def _build_content(
    index: ProjectIndex,
    results: List[QueryResult],
    user_query: str,
    definition: TargetDef,
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    project_overview = (
        f"# {index.projectName}\n"
        f"{definition.header}\n\n"
        f"> Generated by smartctx on {now}\n"
        f'> Task: "{user_query}"\n'
        f"> Showing {len(results)} most relevant files out of {index.totalFiles} total\n\n"
        f"---\n"
    )

    relevant_parts: List[str] = []
    for i, r in enumerate(results):
        exports = (
            f"\n  - **Exports:** {', '.join(r.file.exports[:5])}"
            if r.file.exports else ""
        )
        deps = (
            f"\n  - **Key deps:** {', '.join(r.file.dependencies[:4])}"
            if r.file.dependencies else ""
        )
        tags = (
            f"\n  - **Tags:** {', '.join(r.file.tags)}"
            if r.file.tags else ""
        )
        relevant_parts.append(
            f"### {i + 1}. `{r.file.path}`\n"
            f"  - {r.file.summary}{exports}{deps}{tags}"
        )

    relevant_files = "\n\n".join(relevant_parts)

    all_files = "\n".join(
        f"- `{f.path}` \u2014 {f.summary}" for f in index.files.values()
    )

    footer = (
        f"\n\n---\n\n"
        f"## All Project Files (for reference)\n\n"
        f"{all_files}\n\n"
        f"---\n"
        f"*smartctx \u2014 https://www.npmjs.com/package/smartctx*\n"
        f"*Last full sync: {index.lastSync}*\n"
    )

    return (
        f"{project_overview}\n"
        f"## Relevant Files for Your Task\n\n"
        f"{relevant_files}"
        f"{footer}"
    )


def estimate_tokens_saved(
    total_files: int,
    avg_file_size_bytes: float,
    relevant_files: int,
) -> int:
    full_tokens = (total_files * avg_file_size_bytes) / 4
    smart_tokens = (relevant_files * avg_file_size_bytes) / 4 + 2000
    return max(0, round(full_tokens - smart_tokens))
