from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


@dataclass
class TargetDef:
    name: str
    outputFile: str
    header: str
    detectFiles: List[str] = field(default_factory=list)


BUILT_IN_TARGETS: Dict[str, TargetDef] = {
    "claude": TargetDef(
        name="claude",
        outputFile="CLAUDE.md",
        header=(
            "<!-- Claude Code Context File \u2014 auto-generated by smartctx -->\n"
            "<!-- Read this file to understand the project before making changes -->"
        ),
        detectFiles=["CLAUDE.md", ".claude/"],
    ),
    "cursor": TargetDef(
        name="cursor",
        outputFile=".cursorrules",
        header="# Cursor Rules \u2014 auto-generated by smartctx",
        detectFiles=[".cursorrules", ".cursor/"],
    ),
    "copilot": TargetDef(
        name="copilot",
        outputFile=".github/copilot-instructions.md",
        header="<!-- GitHub Copilot Instructions \u2014 auto-generated by smartctx -->",
        detectFiles=[".github/copilot-instructions.md"],
    ),
    "codex": TargetDef(
        name="codex",
        outputFile="AGENTS.md",
        header="# Agent Instructions \u2014 auto-generated by smartctx",
        detectFiles=["AGENTS.md"],
    ),
    "windsurf": TargetDef(
        name="windsurf",
        outputFile=".windsurfrules",
        header="# Windsurf Rules \u2014 auto-generated by smartctx",
        detectFiles=[".windsurfrules", ".windsurf/"],
    ),
    "cline": TargetDef(
        name="cline",
        outputFile=".clinerules",
        header="# Cline Rules \u2014 auto-generated by smartctx",
        detectFiles=[".clinerules"],
    ),
    "aider": TargetDef(
        name="aider",
        outputFile="CONVENTIONS.md",
        header="# Aider Conventions \u2014 auto-generated by smartctx",
        detectFiles=["CONVENTIONS.md", ".aider.conf.yml"],
    ),
    "continue": TargetDef(
        name="continue",
        outputFile=".continuerules",
        header="# Continue Rules \u2014 auto-generated by smartctx",
        detectFiles=[".continuerules", ".continue/"],
    ),
    "gemini": TargetDef(
        name="gemini",
        outputFile="GEMINI.md",
        header="<!-- Gemini CLI Context \u2014 auto-generated by smartctx -->",
        detectFiles=["GEMINI.md", ".gemini/"],
    ),
    "zed": TargetDef(
        name="zed",
        outputFile=".rules",
        header="# Zed AI Rules \u2014 auto-generated by smartctx",
        detectFiles=[".rules", ".zed/"],
    ),
}

USER_TARGETS_FILE = Path.home() / ".smartctx" / "targets.json"


def load_user_targets() -> Dict[str, TargetDef]:
    if not USER_TARGETS_FILE.exists():
        return {}
    try:
        raw = json.loads(USER_TARGETS_FILE.read_text("utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}

    out: Dict[str, TargetDef] = {}
    for key, value in raw.items():
        if not isinstance(value, dict) or not value.get("outputFile"):
            continue
        out[key] = TargetDef(
            name=value.get("name", key),
            outputFile=value["outputFile"],
            header=value.get("header", f"# {key} \u2014 auto-generated by smartctx"),
            detectFiles=value.get("detectFiles") or [],
        )
    return out


def save_user_targets(targets: Dict[str, TargetDef]) -> None:
    USER_TARGETS_FILE.parent.mkdir(parents=True, exist_ok=True)
    data = {
        k: {
            "name": v.name,
            "outputFile": v.outputFile,
            "header": v.header,
            "detectFiles": v.detectFiles,
        }
        for k, v in targets.items()
    }
    USER_TARGETS_FILE.write_text(json.dumps(data, indent=2), "utf-8")


def get_all_targets() -> Dict[str, TargetDef]:
    merged = dict(BUILT_IN_TARGETS)
    merged.update(load_user_targets())
    return merged


def get_target(name: str) -> Optional[TargetDef]:
    return get_all_targets().get(name.lower())


def add_user_target(definition: TargetDef) -> None:
    user = load_user_targets()
    user[definition.name.lower()] = definition
    save_user_targets(user)


def remove_user_target(name: str) -> bool:
    key = name.lower()
    user = load_user_targets()
    if key not in user:
        return False
    del user[key]
    save_user_targets(user)
    return True


def parse_targets(value: str) -> List[str]:
    return [s.strip().lower() for s in value.split(",") if s.strip()]


def detect_target(project_path: str) -> Optional[str]:
    root = Path(project_path)
    for key, definition in get_all_targets().items():
        for marker in definition.detectFiles or []:
            if (root / marker).exists():
                return key
    return None
